#!/usr/bin/env bash
# Transfers a file to a server using SCP

# Check if there are less than 4 arguments
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi
